### ISSUE TITLE
Please add HoTT to coq-contribs.

### ISSUE THREAD

**Issue by ejgallego** [coq-contribs/coq-contribs#2]
Please add HoTT to coq-contribs.
- https://github.com/HoTT/HoTT

Thanks

**Comment by JasonGross** [comment]
What's the procedure for getting something to be a contrib these days?

**Comment by spitters** [comment]
I guess contacting @matej-kosik ?

Note that HoTT is already in opam. 
Since we are now compatible with 8.5pl1, this can now be simplified.
https://github.com/coq/opam-coq-archive/blob/b0a9bc0da6b1bbc0bf43fc3ea16429a5d64d430e/extra-dev/packages/coq-hott/coq-hott.0.9.0/opam

Is there any progress on the coq_makefile, to facilitate the installation process?
From the opam file:
(\*  Due to limitations in coq_Makefile, we need to build the whole coq, the stdlib and HoTT/HoTT at the same time.
    We hope for a better solution in the future.
    https://github.com/HoTT/HoTT/blob/master/INSTALL.txt *)

**Comment by ejgallego** [comment]
AFAICT the opam file is out of date, using the proper configure you don't need to build a new coq.

**Comment by spitters** [comment]
The problem, as I recall it, is that we use our own version of the stdlib.

coq_makefile would need a flag
-is . Hoq
for us to rename our own std lib.

There was some discussion on _Coqproject and coq_makefile here:
https://github.com/HoTT/HoTT/pull/180

**Comment by spitters** [comment]
From an earlier email discussion with @JasonGross :
Another reason we can't currently use just a _CoqProject is that there's no way to set the coqtop binary in a way PG/CoqIDE understands.

**Comment by JasonGross** [comment]
It's true that we don't need to build a new version of Coq anymore.  However, we still can't use `coq_makefile` (unless we can do something special with subdirectories?), because we need to pass different options to our local standard library than to the rest of the development.

If we move to a generated `_CoqProject` rather than a non-generated one, we can add the relevant flags to `_CoqProject` (`-coqlib coq -R theories HoTT -Q contrib "" -indices-matter`).

**Comment by ejgallego** [comment]
Doing these improvements would be great, but none of them should be blockers for HoTT integration IMHO.

**Comment by spitters** [comment]
We need to fill out [this](http://www.lix.polytechnique.fr/coq/pylons/contribs/new) form.

**Comment by ghost** [comment]
The common properties of all coq-contribs are documented [here](https://github.com/coq-contribs/coq-contribs/blob/master/FAQ.md#what-are-the-common-properties-of-all-coq-contribs).

Is there any hope that HoTT can possibly conform to them?

(I haven't tried to explain the rules; in case if you think the motivation is unclear, please ask for more details)

**Comment by spitters** [comment]
The main issue there might be is the makefile. @JasonGross ?
https://github.com/HoTT/HoTT/blob/master/INSTALL.md

**Comment by JasonGross** [comment]
@matej-kosik does it have to be `Makefile` or can it be `makefile`?  The most lightweight, hackish solution I can think of is to have a `makefile` that builds `Makefile` with `autogen.sh` and `configure` and then includes it, with some make hackery to replace `makefile` on case-insensitive platforms, together with telling git to assume that it's unchanged...

It might be possible to have configure generate the Makefile in a subdirectory or with a different name...

Alternatively, @matej-kosik, would it be possible to extend the rules to allow `./autogen.sh && ./configure && make`?  What's the reasoning behind not allowing this path?

**Comment by JasonGross** [comment]
Also, we currently depend on having autotools / autoreconf installed; is this an issue?

**Comment by ghost** [comment]
The common properties of all coq-contribs are described [here](https://github.com/coq-contribs/coq-contribs/blob/master/FAQ.md#what-are-the-common-properties-of-all-coq-contribs).

Let us talk first about the major roadblock (in my opinion).

All coq-contribs are currently compilable with the HEADs of all of the following branches of Coq:
- `trunk`
- `v8.6`
- `v8.5`

This is feasible in case of coq-contribs, because they are simply "up-ported" from one version of Coq to another. I am not sure how realistic it would be to require this for projects that are intensively worked on, but there certainly is a possible gain for both parties:
- coq-team would be able to evaluate the impact of various ideas on HoTT
- HoTT-team could get some "up-porting" effort for free (if coq-team committed to do this for mutual benefit)

But this model of cooperation was not yet officially discussed, tried and tested.

So far, it happened only with `math-classes` and `corn` and I am not sure if that is comparable with HoTT.

**Comment by ejgallego** [comment]
I have moved to a different integration solution, so closing this; if anyone is interested in taking over please reopen.
